n = input('Digite alguma coisa:')
print('{} É da classe:'.format(n), type(n))
print('{} É só espaço?'.format(n), n.isspace())
print('{} É letra?'.format(n), n.isalpha())
print('{} É numero?'.format(n), n.isnumeric())
print('{} É letra e numero?'.format(n), n.isalnum())
print('{} Esta em maiúscula?'.format(n), n.isupper())
print('{} Esta em minuscula?'.format(n), n.islower())
print('{} Está capitalizada?'.format(n), n.istitle())
